FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Local development port
# EXPOSE 8000

# Ubah expose ke 9000 (Railway pakai ini)
EXPOSE 8005

# Tetap gunakan entry point yang benar
CMD ["node", "src/index.js"]
